version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: cloudcron.app
  login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: endpoints
  version: 1.0
